# Generated by Django 3.0 on 2019-12-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=4000)),
                ('completed', models.BooleanField(default=False)),
                ('audit_cd', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
